### ISSUE TITLE
create react app issue

### ISSUE THREAD

**Issue by maxscience** [wesbos/eslint-config-wesbos#9]
Install could be streamlined a bit as if you install it in create react app projects, you run into this issue (create react app uses "babel-eslint": "9.0.0" and this installs version 10.0.1 )
https://github.com/eslint/eslint/issues/11229

**Comment by wesbos** [comment]
Do you know if there are any downsides to reverting to 9.x?

**Comment by maxscience** [comment]
Not to my knowledge but I'd use the same version as create react app just to be safe.
I 'fixed' the issue the quick way by adding 
```
SKIP_PREFLIGHT_CHECK=true
```
to the .env file.

Another quirk I noticed is 
```
    this.setState({
      order
    });
```
will get linted on save as (notice the comma)
```
    this.setState({
      order,
    });
```

**Comment by wesbos** [comment]
thats because I have the trailing comma setting set to es5

**Comment by wesbos** [comment]
This is fixed :)

**Comment by nikodem-kalinowski** [comment]
Dear @wesbos 

I think you can revert this fix https://github.com/mifas/eslint-config-prettier-react/commit/85038172ee16306db4dc2ea8e58ec65ea795097f because now CRA expects babel-eslint: 10.0.1, can you verify this somehow?
I've tried adding those awesome configs to fresh project started with CRA and got errors regarding babel-eslint being `9.0.0`

**Comment by CuteShaun** [comment]
Hey @wesbos, have the same problem with babel-eslint `9.0.0` and CRA.
